name: build
on: [push]
jobs:
  run_build_script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1' # The Go version to download (if necessary) and use.
    - name: run_build_script
      shell: bash
      run: build.sh
